version: '3'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    depends_on:
      - elasticsearch
      - redis

  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.14.0
    ports:
      - "9200:9200"
    environment:
      - discovery.type=single-node

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
